name: etalons
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  expandable: ^5.0.1
  flutter_svg: ^2.1.0
  logging: ^1.1.1
  firebase_core: ^2.20.0
  firebase_crashlytics: ^3.3.0
  json_annotation: ^4.8.1
  intl: ^0.18.0
  flutter_speed_dial: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/