name: etalons
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.3.8
  hive_flutter: ^1.1.0
  expandable: ^5.0.1
  flutter_svg: ^2.1.0
  logging: ^1.1.1
  firebase_core: ^2.24.0
  firebase_crashlytics: ^3.5.3
  json_annotation: ^6.6.2
  hive_generator: ^2.2.0
  hive: ^2.3.1
  intl: ^0.18.1
  flutter_speed_dial: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/