name: Flutter Android Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.6 # Compatible stable Flutter version
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Generate Hive & JSON files
        run: flutter pub run build_runner build --delete-conflicting-outputs
        continue-on-error: true  # Skip errors if build_runner fails

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: etalons-apk
          path: build/app/outputs/flutter-apk/app-release.apk