name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: stable

    - name: Install dependencies
      run: flutter pub get

    - name: Generate Hive & JSON files
      run: flutter pub run build_runner build --delete-conflicting-outputs

    - name: Build APK
      run: flutter build apk --debug --no-shrink