name: Android Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Flutter with a version that supports Dart >=3.1
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.13.1
          channel: stable

      # Enable Flutter analytics off
      - name: Disable Flutter analytics
        run: flutter config --no-analytics

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Generate Hive TypeAdapters and JSON serialization files
      - name: Build runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      # Build the APK
      - name: Build APK
        run: flutter build apk --release

      # Upload the APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: etalons-apk
          path: build/app/outputs/flutter-apk/app-release.apk